#!/usr/bin/env bash
vncver='3.0.0'

# check docker image for packaging
if [ $# == 0 ]; then
  echo "Build Docker image as zvnc:$vncver"
  docker image build --compress -t zvnc:$vncver -f ./Dockerfile .
fi

if [ "$(docker images -q zvnc:$vncver 2> /dev/null)" == "" ]; then
  echo "Build Docker image as zvnc:$vncver"
  docker image build --compress -t zvnc:$vncver -f ./Dockerfile .
f
fi

# execute commands 
if [ $# -ne 0 ]; then
  echo "$@ ..."
  docker run -v $HOME:$HOME -v `pwd`:`pwd` -w `pwd` -i -t --rm --network host zvnc:$vncver $@
else
  echo "Start services ..."
  docker run -v $HOME:$HOME -v `pwd`:`pwd` -w `pwd` -d --restart=on-failure --network host zvnc:$vncver
fi
